### ISSUE TITLE
Still not possible to login after install

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/gancio_ynh#13]
### Describe the bug

Hang at end of install process and not possible to login after.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.12 (stable)
- I have access to my server: *Through SSH | through the webadmin*

### Steps to reproduce

   1. *Go to `App catalogue`*
   2. *Click on 'Install Gancio'*
   4. No Error Message, the install process hang at last step (`Gancio Installée`).
   5. Go to Gancio URL (it's running) and try to login as admin (fail).
   6. Error*: `Impossible de se connecter. Veuillez vérifier vos informations de connexion`

Note: same problem with CLI, just the install process doesn't hang at the end.

### Expected behavior

*Having a working Gancio Instance ;-).*

### Logs

- Web UI install: https://paste.yunohost.org/raw/lohakizifu
- CLI install: https://paste.yunohost.org/raw/akiveharux

**Comment by bugsysop** [comment]
Hang of install process was a browser problem (Gnome Web). No problem with Vivaldi and FirefoX... But still can't login.

**Comment by lesion** [comment]
you can register an user, the first one will be an administrator

**Comment by bugsysop** [comment]
@lesion 

Worked fine...

Explanation : actually **YNH install script** doesn't create any admin user (bug).

**Comment by lapineige** [comment]
> Explanation : actually YNH install script doesn't create any admin user (bug).

Let's keep this open then.

**Comment by bugsysop** [comment]
I confirm, problem solved with the `fix-admin2` branch.
