### ISSUE TITLE
Still not possible to login after install (saison II)

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/gancio_ynh#22]
Follow up of issue #13 (sorry for insisting)

With le new package version (`1.16.2~ynh1`) the login problem is still not solved… and quite _whorst_ in fact.

1. Admin user is created at install…
2. but admin user can't login.
3. New user can register…
4. but new user can't login because wait for validation by admin.
5. Turn to point `1.`

The whorst part is this: now we can't use anymore the hacky solution suggested [here](https://github.com/YunoHost-Apps/gancio_ynh/issues/13#issuecomment-2132856566) by @lesion 

<del>Is there a way to install the previous version of YNH Gancio App (`1.15.5~ynh1` if I remember)?</del>

Update - Managed to install `1.15.5~ynh1` from this fork: https://github.com/bugsysop/gancio_ynh/tree/master

**Comment by tituspijean** [comment]
> but admin user can't login.

Works for me, if I use the admin's email as per requested in the login form.

**Comment by bugsysop** [comment]
Found the problem: I was connected to _another_ Gancio Instance... I don't know why, but if your are logged to an instance, you can't login to another with _no explicit error message_.

I have the same problem with Pleroma.

**Comment by lapineige** [comment]
On the same server you mean ?

**Comment by bugsysop** [comment]
No ! You can't have two Gancio (or Pleroma) on same server... Eatch instance of Gancio is on a separate YNH install on a different VPS.
