### ISSUE TITLE
Gancio install fails

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/gancio_ynh#23]
Message on install: 
`Failed to download asset 'main' (https://gancio.org/releases/gancio-v1.16.2.tgz) for gancio: Will not apply HSTS. The HSTS database must be a regular and non-world-writable file. ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled. failed: No route to host. 
`
- Hardware: * Old laptop or computer *
- YunoHost version: 11.2.14.1 (stable)
- I have access to my server: *Through SSH *
- Using, or trying to install package version/branch: 1.16.2~ynh1
 
### Logs

 https://paste.yunohost.org/raw/niyaxuhexu

**Comment by cloo** [comment]
Is it expected to be fixed in hours, days or months? So we could have an idea if it is worth waiting.

**Comment by lesion** [comment]
> Is it expected to be fixed in hours, days or months? So we could have an idea if it is worth waiting.

I'm in your very same situation :smile: 
![immagine](https://github.com/YunoHost-Apps/gancio_ynh/assets/504700/3b3d0c23-7b91-4140-a1d3-3fea80ebbddb)

**Comment by lesion** [comment]
You can try now
