### ISSUE TITLE
app can't be installed more than once

### ISSUE THREAD

**Issue by kamazeuci** [YunoHost-Apps/gancio_ynh#25]
I was about to install gancio on another domain, for another project(because I loved the experience on my first one) but YNH says it can only be installed once :-(
Why is this? is this temporal? is there a workaround?

thanks

**Comment by lesion** [comment]
For reference, I think it's because of the following:  
https://github.com/YunoHost-Apps/gancio_ynh/blob/master/manifest.toml#L24

**Comment by lapineige** [comment]
I used that setting to make it simple for the first packaging steps.
I don't remember if the app can or can't be installed multiple times.

@kamazeuci you can try #26 once the continuous integration tests are done and all good.

**Comment by lesion** [comment]
> I used that setting to make it simple for the first packaging steps. I don't remember if the app can or can't be installed multiple times.


do you know what the requirements are?
I currently have multiple instances of gancio on the same machine running on different ports and with different db's so it can be done.
thanks!

> @kamazeuci you can try #26 once the continuous integration tests are done and all good.

**Comment by lapineige** [comment]
> do you know what the requirements are?

No idea. It should be lightweight.

**Comment by kamazeuci** [comment]
solved in #26
