### ISSUE TITLE
can't login after latest (1.19.0~ynh1) update

### ISSUE THREAD

**Issue by kamazeuci** [YunoHost-Apps/gancio_ynh#31]
Just updated to 1.19.0~ynh1 and now I can't login with any of the users.
If I try to recover password I do get the email and change password to a new one but it still doesn't work.

**Comment by kamazeuci** [comment]
here is the upgrade log
https://paste.yunohost.org/raw/uxoyicoted

**Comment by kamazeuci** [comment]
Update accesses for permission 'gancio'
```
2024-09-13 14:10:05,557: DEBUG - Nothing to update in LDAP
2024-09-13 14:10:05,561: DEBUG - Permission 'gancio.main' updated
```

Update URL related to permission 'gancio'
```
2024-09-13 14:10:05,608: DEBUG - Nothing to update in LDAP
2024-09-13 14:10:05,608: DEBUG - Permission 'gancio.main' updated
```

**Comment by lapineige** [comment]
That's strange, nothing except the version changed here : https://github.com/YunoHost-Apps/gancio_ynh/pull/30 :(

I'd suggest to revert to the automated backup while someone investigate this bug.

**Comment by kamazeuci** [comment]
I have no idea what happened... today it just works. Did no change at all. the other day I tried with different accounts, even resetting passwords... spent a lot of time on it...
well, it will remain a mistery but problem is solved. 
thanks.

**Comment by lapineige** [comment]
That's weird... but anyway that's great in the end :)
