### ISSUE TITLE
1.14 update

### ISSUE THREAD

**Issue by jcrabapple** [YunoHost-Apps/gancio_ynh#5]
The 1.14 update is available from the main repo. Please update the yunohost repo, as there are many fixes around federation in the recent months. Thank you.

**Comment by lapineige** [comment]
We are aware of the update, I subscribed to the notification.
Creating a pull request is quite simple for such an update, you change the URL in the manifest file, you enter the new SHA256 sum, and it's done. Contributions welcome :)
